export const siteConfig = {
  name: "afto.works",
  shortName: "afto",
  description: "Projektuję nowoczesne strony internetowe, UI/UX i branding. Zobacz portfolio i rozpocznij projekt.",
  url: "https://afto.works",
  locale: "pl_PL",
  keywords: [
    "projektowanie stron",
    "strony internetowe",
    "web design",
    "UI UX",
    "projektant stron",
    "tworzenie stron internetowych",
    "design stron",
    "branding",
    "identyfikacja wizualna",
    "portfolio design",
    "projektowanie UI",
    "minecraft design",
    "grafiki minecraft",
    "design serwer minecraft",
    "strony dla serwerów minecraft",
    "hosting minecraft strona design",
    "itemshop minecraft design",
    "sklep serwer minecraft UI",
    "grafiki gamingowe",
    "gaming UI",
    "afto",
    "afto works",
  ],
  ogImage: "/Social_preview.png",
};
